export const DEFAULT_DRESS_SHIRTS = [
  {
    name: "White Button-Down Dress Shirt",
    category: "tops",
    primary_color: "White",
    color_hex: "#FFFFFF",
    style_tags: ["neutral", "minimal"],
    photo_url: "/wardrobe/shirt-white.jpeg",
    is_new: false,
    is_featured: true,
  },
  {
    name: "Purple Button-Down Dress Shirt",
    category: "tops",
    primary_color: "Purple",
    color_hex: "#7B2D8E",
    style_tags: ["bold"],
    photo_url: "/wardrobe/shirt-purple.jpeg",
    is_new: false,
    is_featured: false,
  },
  {
    name: "Pink Button-Down Dress Shirt",
    category: "tops",
    primary_color: "Pink",
    color_hex: "#F4C2C2",
    style_tags: ["casual", "bold"],
    photo_url: "/wardrobe/shirt-pink.jpeg",
    is_new: false,
    is_featured: false,
  },
  {
    name: "Black Button-Down Dress Shirt",
    category: "tops",
    primary_color: "Black",
    color_hex: "#1A1A1A",
    style_tags: ["minimal", "luxury"],
    photo_url: "/wardrobe/shirt-black.jpeg",
    is_new: false,
    is_featured: false,
  },
  {
    name: "Dark Navy Button-Down Dress Shirt",
    category: "tops",
    primary_color: "Dark Navy",
    color_hex: "#1B2A4A",
    style_tags: ["neutral", "minimal"],
    photo_url: "/wardrobe/shirt-navy.jpeg",
    is_new: false,
    is_featured: false,
  },
  {
    name: "Light Gray Button-Down Dress Shirt",
    category: "tops",
    primary_color: "Light Gray",
    color_hex: "#C8C8C8",
    style_tags: ["neutral", "minimal"],
    photo_url: "/wardrobe/shirt-light-gray.jpeg",
    is_new: false,
    is_featured: false,
  },
  {
    name: "Dark Storm Gray Button-Down Dress Shirt",
    category: "tops",
    primary_color: "Dark Storm Gray",
    color_hex: "#4A4E54",
    style_tags: ["neutral", "minimal"],
    photo_url: "/wardrobe/shirt-storm-gray.jpeg",
    is_new: false,
    is_featured: false,
  },
];
